name: biliup-master # 名称随意
on: 
  workflow_dispatch: 
  schedule: 
  - cron: '19 */3 * * *'
  # watch: 
   # types: started 
  # repository_dispatch:
    # types: ark
jobs: 
 repo-sync: 
     env: 
       PAT: ${{ secrets.PAT }} 
     runs-on: ubuntu-latest 
     # if: github.event.repository.owner.id == github.event.sender.id 
     steps: 
      - uses: actions/checkout@v2 
        with: 
          persist-credentials: false 
    
      - name: sync biliup-master
        uses: repo-sync/github-sync@v2 
        if: env.PAT 
        with: 
          source_repo: "https://github.com/biliup/biliup.git" # 上游仓库地址
          source_branch: "master" 
          destination_branch: "biliup-master" # 按照自己仓库分支名称修改
          github_token: ${{ secrets.PAT }} 
